docs: document experimental astro plugin
LyraSearch/docs pull request #3
Opened 2022-08-22 18:21 UTC by castarco

Signed-off-by: Andres Correa Casablanca <castarco@coderspirit.xyz>

2022-08-23 14:05 UTC, micheleriva requested changes

2022-08-23 14:05 UTC, micheleriva commented on docs/plugins/plugin-astro.mdx
> +| Node.js        | ✅ &nbsp;available          |
I think we could remove this table as I think Astro is supported on Node.js exclusively, right?

2022-08-23 14:37 UTC, castarco commented on docs/plugins/plugin-astro.mdx
> +| Node.js        | ✅ &nbsp;available          |
Not exactly, it supports other "engines" for its SSR features: https://docs.astro.build/en/guides/server-side-rendering/

2022-08-23 18:19 UTC, castarco commented on docs/plugins/plugin-astro.mdx
> +| Node.js        | ✅ &nbsp;available          |
I added a reference to SSR support on Astro, to contextualize what's possible on this plugin's side.

2022-08-24 08:13 UTC, micheleriva approved these changes

2022-08-24 08:13 UTC, merged